// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: MessageObject.proto

package com.wisekrakr.wisesecurecomm.communication.proto;

/**
 * Protobuf type {@code com.wisekrakr.wisesecurecomm.communication.proto.MessageObject}
 */
public final class MessageObject extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:com.wisekrakr.wisesecurecomm.communication.proto.MessageObject)
    MessageObjectOrBuilder {
private static final long serialVersionUID = 0L;
  // Use MessageObject.newBuilder() to construct.
  private MessageObject(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private MessageObject() {
    objectType_ = 0;
    textMessage_ = "";
    voiceMessage_ = com.google.protobuf.ByteString.EMPTY;
    recipientsIds_ = emptyLongList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new MessageObject();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private MessageObject(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {

            id_ = input.readInt64();
            break;
          }
          case 16: {
            int rawValue = input.readEnum();

            objectType_ = rawValue;
            break;
          }
          case 26: {
            com.wisekrakr.wisesecurecomm.communication.proto.MessageType.Builder subBuilder = null;
            if (messageType_ != null) {
              subBuilder = messageType_.toBuilder();
            }
            messageType_ = input.readMessage(com.wisekrakr.wisesecurecomm.communication.proto.MessageType.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(messageType_);
              messageType_ = subBuilder.buildPartial();
            }

            break;
          }
          case 34: {
            java.lang.String s = input.readStringRequireUtf8();

            textMessage_ = s;
            break;
          }
          case 42: {

            voiceMessage_ = input.readBytes();
            break;
          }
          case 50: {
            com.wisekrakr.wisesecurecomm.communication.proto.FileInfo.Builder subBuilder = null;
            if (fileInfo_ != null) {
              subBuilder = fileInfo_.toBuilder();
            }
            fileInfo_ = input.readMessage(com.wisekrakr.wisesecurecomm.communication.proto.FileInfo.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(fileInfo_);
              fileInfo_ = subBuilder.buildPartial();
            }

            break;
          }
          case 56: {

            ownerId_ = input.readInt64();
            break;
          }
          case 64: {
            if (!((mutable_bitField0_ & 0x00000001) != 0)) {
              recipientsIds_ = newLongList();
              mutable_bitField0_ |= 0x00000001;
            }
            recipientsIds_.addLong(input.readInt64());
            break;
          }
          case 66: {
            int length = input.readRawVarint32();
            int limit = input.pushLimit(length);
            if (!((mutable_bitField0_ & 0x00000001) != 0) && input.getBytesUntilLimit() > 0) {
              recipientsIds_ = newLongList();
              mutable_bitField0_ |= 0x00000001;
            }
            while (input.getBytesUntilLimit() > 0) {
              recipientsIds_.addLong(input.readInt64());
            }
            input.popLimit(limit);
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) != 0)) {
        recipientsIds_.makeImmutable(); // C
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.wisekrakr.wisesecurecomm.communication.proto.MessageObjectOuterClass.internal_static_com_wisekrakr_wisesecurecomm_communication_proto_MessageObject_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.wisekrakr.wisesecurecomm.communication.proto.MessageObjectOuterClass.internal_static_com_wisekrakr_wisesecurecomm_communication_proto_MessageObject_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.wisekrakr.wisesecurecomm.communication.proto.MessageObject.class, com.wisekrakr.wisesecurecomm.communication.proto.MessageObject.Builder.class);
  }

  /**
   * Protobuf enum {@code com.wisekrakr.wisesecurecomm.communication.proto.MessageObject.ObjectType}
   */
  public enum ObjectType
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>MESSAGE = 0;</code>
     */
    MESSAGE(0),
    /**
     * <code>NOTIFICATION = 1;</code>
     */
    NOTIFICATION(1),
    /**
     * <code>COMMAND = 2;</code>
     */
    COMMAND(2),
    /**
     * <code>SECURITY = 3;</code>
     */
    SECURITY(3),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>MESSAGE = 0;</code>
     */
    public static final int MESSAGE_VALUE = 0;
    /**
     * <code>NOTIFICATION = 1;</code>
     */
    public static final int NOTIFICATION_VALUE = 1;
    /**
     * <code>COMMAND = 2;</code>
     */
    public static final int COMMAND_VALUE = 2;
    /**
     * <code>SECURITY = 3;</code>
     */
    public static final int SECURITY_VALUE = 3;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static ObjectType valueOf(int value) {
      return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static ObjectType forNumber(int value) {
      switch (value) {
        case 0: return MESSAGE;
        case 1: return NOTIFICATION;
        case 2: return COMMAND;
        case 3: return SECURITY;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<ObjectType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        ObjectType> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<ObjectType>() {
            public ObjectType findValueByNumber(int number) {
              return ObjectType.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalStateException(
            "Can't get the descriptor of an unrecognized enum value.");
      }
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.wisekrakr.wisesecurecomm.communication.proto.MessageObject.getDescriptor().getEnumTypes().get(0);
    }

    private static final ObjectType[] VALUES = values();

    public static ObjectType valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private ObjectType(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:com.wisekrakr.wisesecurecomm.communication.proto.MessageObject.ObjectType)
  }

  public static final int ID_FIELD_NUMBER = 1;
  private long id_;
  /**
   * <code>int64 id = 1;</code>
   * @return The id.
   */
  @java.lang.Override
  public long getId() {
    return id_;
  }

  public static final int OBJECT_TYPE_FIELD_NUMBER = 2;
  private int objectType_;
  /**
   * <code>.com.wisekrakr.wisesecurecomm.communication.proto.MessageObject.ObjectType object_type = 2;</code>
   * @return The enum numeric value on the wire for objectType.
   */
  @java.lang.Override public int getObjectTypeValue() {
    return objectType_;
  }
  /**
   * <code>.com.wisekrakr.wisesecurecomm.communication.proto.MessageObject.ObjectType object_type = 2;</code>
   * @return The objectType.
   */
  @java.lang.Override public com.wisekrakr.wisesecurecomm.communication.proto.MessageObject.ObjectType getObjectType() {
    @SuppressWarnings("deprecation")
    com.wisekrakr.wisesecurecomm.communication.proto.MessageObject.ObjectType result = com.wisekrakr.wisesecurecomm.communication.proto.MessageObject.ObjectType.valueOf(objectType_);
    return result == null ? com.wisekrakr.wisesecurecomm.communication.proto.MessageObject.ObjectType.UNRECOGNIZED : result;
  }

  public static final int MESSAGE_TYPE_FIELD_NUMBER = 3;
  private com.wisekrakr.wisesecurecomm.communication.proto.MessageType messageType_;
  /**
   * <code>.com.wisekrakr.wisesecurecomm.communication.proto.MessageType message_type = 3;</code>
   * @return Whether the messageType field is set.
   */
  @java.lang.Override
  public boolean hasMessageType() {
    return messageType_ != null;
  }
  /**
   * <code>.com.wisekrakr.wisesecurecomm.communication.proto.MessageType message_type = 3;</code>
   * @return The messageType.
   */
  @java.lang.Override
  public com.wisekrakr.wisesecurecomm.communication.proto.MessageType getMessageType() {
    return messageType_ == null ? com.wisekrakr.wisesecurecomm.communication.proto.MessageType.getDefaultInstance() : messageType_;
  }
  /**
   * <code>.com.wisekrakr.wisesecurecomm.communication.proto.MessageType message_type = 3;</code>
   */
  @java.lang.Override
  public com.wisekrakr.wisesecurecomm.communication.proto.MessageTypeOrBuilder getMessageTypeOrBuilder() {
    return getMessageType();
  }

  public static final int TEXT_MESSAGE_FIELD_NUMBER = 4;
  private volatile java.lang.Object textMessage_;
  /**
   * <code>string text_message = 4;</code>
   * @return The textMessage.
   */
  @java.lang.Override
  public java.lang.String getTextMessage() {
    java.lang.Object ref = textMessage_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      textMessage_ = s;
      return s;
    }
  }
  /**
   * <code>string text_message = 4;</code>
   * @return The bytes for textMessage.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getTextMessageBytes() {
    java.lang.Object ref = textMessage_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      textMessage_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int VOICE_MESSAGE_FIELD_NUMBER = 5;
  private com.google.protobuf.ByteString voiceMessage_;
  /**
   * <code>bytes voice_message = 5;</code>
   * @return The voiceMessage.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString getVoiceMessage() {
    return voiceMessage_;
  }

  public static final int FILE_INFO_FIELD_NUMBER = 6;
  private com.wisekrakr.wisesecurecomm.communication.proto.FileInfo fileInfo_;
  /**
   * <code>.com.wisekrakr.wisesecurecomm.communication.proto.FileInfo file_info = 6;</code>
   * @return Whether the fileInfo field is set.
   */
  @java.lang.Override
  public boolean hasFileInfo() {
    return fileInfo_ != null;
  }
  /**
   * <code>.com.wisekrakr.wisesecurecomm.communication.proto.FileInfo file_info = 6;</code>
   * @return The fileInfo.
   */
  @java.lang.Override
  public com.wisekrakr.wisesecurecomm.communication.proto.FileInfo getFileInfo() {
    return fileInfo_ == null ? com.wisekrakr.wisesecurecomm.communication.proto.FileInfo.getDefaultInstance() : fileInfo_;
  }
  /**
   * <code>.com.wisekrakr.wisesecurecomm.communication.proto.FileInfo file_info = 6;</code>
   */
  @java.lang.Override
  public com.wisekrakr.wisesecurecomm.communication.proto.FileInfoOrBuilder getFileInfoOrBuilder() {
    return getFileInfo();
  }

  public static final int OWNER_ID_FIELD_NUMBER = 7;
  private long ownerId_;
  /**
   * <code>int64 owner_id = 7;</code>
   * @return The ownerId.
   */
  @java.lang.Override
  public long getOwnerId() {
    return ownerId_;
  }

  public static final int RECIPIENTS_IDS_FIELD_NUMBER = 8;
  private com.google.protobuf.Internal.LongList recipientsIds_;
  /**
   * <code>repeated int64 recipients_ids = 8;</code>
   * @return A list containing the recipientsIds.
   */
  @java.lang.Override
  public java.util.List<java.lang.Long>
      getRecipientsIdsList() {
    return recipientsIds_;
  }
  /**
   * <code>repeated int64 recipients_ids = 8;</code>
   * @return The count of recipientsIds.
   */
  public int getRecipientsIdsCount() {
    return recipientsIds_.size();
  }
  /**
   * <code>repeated int64 recipients_ids = 8;</code>
   * @param index The index of the element to return.
   * @return The recipientsIds at the given index.
   */
  public long getRecipientsIds(int index) {
    return recipientsIds_.getLong(index);
  }
  private int recipientsIdsMemoizedSerializedSize = -1;

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    getSerializedSize();
    if (id_ != 0L) {
      output.writeInt64(1, id_);
    }
    if (objectType_ != com.wisekrakr.wisesecurecomm.communication.proto.MessageObject.ObjectType.MESSAGE.getNumber()) {
      output.writeEnum(2, objectType_);
    }
    if (messageType_ != null) {
      output.writeMessage(3, getMessageType());
    }
    if (!getTextMessageBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, textMessage_);
    }
    if (!voiceMessage_.isEmpty()) {
      output.writeBytes(5, voiceMessage_);
    }
    if (fileInfo_ != null) {
      output.writeMessage(6, getFileInfo());
    }
    if (ownerId_ != 0L) {
      output.writeInt64(7, ownerId_);
    }
    if (getRecipientsIdsList().size() > 0) {
      output.writeUInt32NoTag(66);
      output.writeUInt32NoTag(recipientsIdsMemoizedSerializedSize);
    }
    for (int i = 0; i < recipientsIds_.size(); i++) {
      output.writeInt64NoTag(recipientsIds_.getLong(i));
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (id_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(1, id_);
    }
    if (objectType_ != com.wisekrakr.wisesecurecomm.communication.proto.MessageObject.ObjectType.MESSAGE.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(2, objectType_);
    }
    if (messageType_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, getMessageType());
    }
    if (!getTextMessageBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, textMessage_);
    }
    if (!voiceMessage_.isEmpty()) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(5, voiceMessage_);
    }
    if (fileInfo_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(6, getFileInfo());
    }
    if (ownerId_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(7, ownerId_);
    }
    {
      int dataSize = 0;
      for (int i = 0; i < recipientsIds_.size(); i++) {
        dataSize += com.google.protobuf.CodedOutputStream
          .computeInt64SizeNoTag(recipientsIds_.getLong(i));
      }
      size += dataSize;
      if (!getRecipientsIdsList().isEmpty()) {
        size += 1;
        size += com.google.protobuf.CodedOutputStream
            .computeInt32SizeNoTag(dataSize);
      }
      recipientsIdsMemoizedSerializedSize = dataSize;
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.wisekrakr.wisesecurecomm.communication.proto.MessageObject)) {
      return super.equals(obj);
    }
    com.wisekrakr.wisesecurecomm.communication.proto.MessageObject other = (com.wisekrakr.wisesecurecomm.communication.proto.MessageObject) obj;

    if (getId()
        != other.getId()) return false;
    if (objectType_ != other.objectType_) return false;
    if (hasMessageType() != other.hasMessageType()) return false;
    if (hasMessageType()) {
      if (!getMessageType()
          .equals(other.getMessageType())) return false;
    }
    if (!getTextMessage()
        .equals(other.getTextMessage())) return false;
    if (!getVoiceMessage()
        .equals(other.getVoiceMessage())) return false;
    if (hasFileInfo() != other.hasFileInfo()) return false;
    if (hasFileInfo()) {
      if (!getFileInfo()
          .equals(other.getFileInfo())) return false;
    }
    if (getOwnerId()
        != other.getOwnerId()) return false;
    if (!getRecipientsIdsList()
        .equals(other.getRecipientsIdsList())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + ID_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getId());
    hash = (37 * hash) + OBJECT_TYPE_FIELD_NUMBER;
    hash = (53 * hash) + objectType_;
    if (hasMessageType()) {
      hash = (37 * hash) + MESSAGE_TYPE_FIELD_NUMBER;
      hash = (53 * hash) + getMessageType().hashCode();
    }
    hash = (37 * hash) + TEXT_MESSAGE_FIELD_NUMBER;
    hash = (53 * hash) + getTextMessage().hashCode();
    hash = (37 * hash) + VOICE_MESSAGE_FIELD_NUMBER;
    hash = (53 * hash) + getVoiceMessage().hashCode();
    if (hasFileInfo()) {
      hash = (37 * hash) + FILE_INFO_FIELD_NUMBER;
      hash = (53 * hash) + getFileInfo().hashCode();
    }
    hash = (37 * hash) + OWNER_ID_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getOwnerId());
    if (getRecipientsIdsCount() > 0) {
      hash = (37 * hash) + RECIPIENTS_IDS_FIELD_NUMBER;
      hash = (53 * hash) + getRecipientsIdsList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.wisekrakr.wisesecurecomm.communication.proto.MessageObject parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.wisekrakr.wisesecurecomm.communication.proto.MessageObject parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.wisekrakr.wisesecurecomm.communication.proto.MessageObject parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.wisekrakr.wisesecurecomm.communication.proto.MessageObject parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.wisekrakr.wisesecurecomm.communication.proto.MessageObject parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.wisekrakr.wisesecurecomm.communication.proto.MessageObject parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.wisekrakr.wisesecurecomm.communication.proto.MessageObject parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.wisekrakr.wisesecurecomm.communication.proto.MessageObject parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.wisekrakr.wisesecurecomm.communication.proto.MessageObject parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.wisekrakr.wisesecurecomm.communication.proto.MessageObject parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.wisekrakr.wisesecurecomm.communication.proto.MessageObject parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.wisekrakr.wisesecurecomm.communication.proto.MessageObject parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.wisekrakr.wisesecurecomm.communication.proto.MessageObject prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code com.wisekrakr.wisesecurecomm.communication.proto.MessageObject}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:com.wisekrakr.wisesecurecomm.communication.proto.MessageObject)
      com.wisekrakr.wisesecurecomm.communication.proto.MessageObjectOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.wisekrakr.wisesecurecomm.communication.proto.MessageObjectOuterClass.internal_static_com_wisekrakr_wisesecurecomm_communication_proto_MessageObject_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.wisekrakr.wisesecurecomm.communication.proto.MessageObjectOuterClass.internal_static_com_wisekrakr_wisesecurecomm_communication_proto_MessageObject_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.wisekrakr.wisesecurecomm.communication.proto.MessageObject.class, com.wisekrakr.wisesecurecomm.communication.proto.MessageObject.Builder.class);
    }

    // Construct using com.wisekrakr.wisesecurecomm.communication.proto.MessageObject.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      id_ = 0L;

      objectType_ = 0;

      if (messageTypeBuilder_ == null) {
        messageType_ = null;
      } else {
        messageType_ = null;
        messageTypeBuilder_ = null;
      }
      textMessage_ = "";

      voiceMessage_ = com.google.protobuf.ByteString.EMPTY;

      if (fileInfoBuilder_ == null) {
        fileInfo_ = null;
      } else {
        fileInfo_ = null;
        fileInfoBuilder_ = null;
      }
      ownerId_ = 0L;

      recipientsIds_ = emptyLongList();
      bitField0_ = (bitField0_ & ~0x00000001);
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.wisekrakr.wisesecurecomm.communication.proto.MessageObjectOuterClass.internal_static_com_wisekrakr_wisesecurecomm_communication_proto_MessageObject_descriptor;
    }

    @java.lang.Override
    public com.wisekrakr.wisesecurecomm.communication.proto.MessageObject getDefaultInstanceForType() {
      return com.wisekrakr.wisesecurecomm.communication.proto.MessageObject.getDefaultInstance();
    }

    @java.lang.Override
    public com.wisekrakr.wisesecurecomm.communication.proto.MessageObject build() {
      com.wisekrakr.wisesecurecomm.communication.proto.MessageObject result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.wisekrakr.wisesecurecomm.communication.proto.MessageObject buildPartial() {
      com.wisekrakr.wisesecurecomm.communication.proto.MessageObject result = new com.wisekrakr.wisesecurecomm.communication.proto.MessageObject(this);
      int from_bitField0_ = bitField0_;
      result.id_ = id_;
      result.objectType_ = objectType_;
      if (messageTypeBuilder_ == null) {
        result.messageType_ = messageType_;
      } else {
        result.messageType_ = messageTypeBuilder_.build();
      }
      result.textMessage_ = textMessage_;
      result.voiceMessage_ = voiceMessage_;
      if (fileInfoBuilder_ == null) {
        result.fileInfo_ = fileInfo_;
      } else {
        result.fileInfo_ = fileInfoBuilder_.build();
      }
      result.ownerId_ = ownerId_;
      if (((bitField0_ & 0x00000001) != 0)) {
        recipientsIds_.makeImmutable();
        bitField0_ = (bitField0_ & ~0x00000001);
      }
      result.recipientsIds_ = recipientsIds_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.wisekrakr.wisesecurecomm.communication.proto.MessageObject) {
        return mergeFrom((com.wisekrakr.wisesecurecomm.communication.proto.MessageObject)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.wisekrakr.wisesecurecomm.communication.proto.MessageObject other) {
      if (other == com.wisekrakr.wisesecurecomm.communication.proto.MessageObject.getDefaultInstance()) return this;
      if (other.getId() != 0L) {
        setId(other.getId());
      }
      if (other.objectType_ != 0) {
        setObjectTypeValue(other.getObjectTypeValue());
      }
      if (other.hasMessageType()) {
        mergeMessageType(other.getMessageType());
      }
      if (!other.getTextMessage().isEmpty()) {
        textMessage_ = other.textMessage_;
        onChanged();
      }
      if (other.getVoiceMessage() != com.google.protobuf.ByteString.EMPTY) {
        setVoiceMessage(other.getVoiceMessage());
      }
      if (other.hasFileInfo()) {
        mergeFileInfo(other.getFileInfo());
      }
      if (other.getOwnerId() != 0L) {
        setOwnerId(other.getOwnerId());
      }
      if (!other.recipientsIds_.isEmpty()) {
        if (recipientsIds_.isEmpty()) {
          recipientsIds_ = other.recipientsIds_;
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          ensureRecipientsIdsIsMutable();
          recipientsIds_.addAll(other.recipientsIds_);
        }
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.wisekrakr.wisesecurecomm.communication.proto.MessageObject parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.wisekrakr.wisesecurecomm.communication.proto.MessageObject) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private long id_ ;
    /**
     * <code>int64 id = 1;</code>
     * @return The id.
     */
    @java.lang.Override
    public long getId() {
      return id_;
    }
    /**
     * <code>int64 id = 1;</code>
     * @param value The id to set.
     * @return This builder for chaining.
     */
    public Builder setId(long value) {
      
      id_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int64 id = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearId() {
      
      id_ = 0L;
      onChanged();
      return this;
    }

    private int objectType_ = 0;
    /**
     * <code>.com.wisekrakr.wisesecurecomm.communication.proto.MessageObject.ObjectType object_type = 2;</code>
     * @return The enum numeric value on the wire for objectType.
     */
    @java.lang.Override public int getObjectTypeValue() {
      return objectType_;
    }
    /**
     * <code>.com.wisekrakr.wisesecurecomm.communication.proto.MessageObject.ObjectType object_type = 2;</code>
     * @param value The enum numeric value on the wire for objectType to set.
     * @return This builder for chaining.
     */
    public Builder setObjectTypeValue(int value) {
      
      objectType_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>.com.wisekrakr.wisesecurecomm.communication.proto.MessageObject.ObjectType object_type = 2;</code>
     * @return The objectType.
     */
    @java.lang.Override
    public com.wisekrakr.wisesecurecomm.communication.proto.MessageObject.ObjectType getObjectType() {
      @SuppressWarnings("deprecation")
      com.wisekrakr.wisesecurecomm.communication.proto.MessageObject.ObjectType result = com.wisekrakr.wisesecurecomm.communication.proto.MessageObject.ObjectType.valueOf(objectType_);
      return result == null ? com.wisekrakr.wisesecurecomm.communication.proto.MessageObject.ObjectType.UNRECOGNIZED : result;
    }
    /**
     * <code>.com.wisekrakr.wisesecurecomm.communication.proto.MessageObject.ObjectType object_type = 2;</code>
     * @param value The objectType to set.
     * @return This builder for chaining.
     */
    public Builder setObjectType(com.wisekrakr.wisesecurecomm.communication.proto.MessageObject.ObjectType value) {
      if (value == null) {
        throw new NullPointerException();
      }
      
      objectType_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>.com.wisekrakr.wisesecurecomm.communication.proto.MessageObject.ObjectType object_type = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearObjectType() {
      
      objectType_ = 0;
      onChanged();
      return this;
    }

    private com.wisekrakr.wisesecurecomm.communication.proto.MessageType messageType_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.wisekrakr.wisesecurecomm.communication.proto.MessageType, com.wisekrakr.wisesecurecomm.communication.proto.MessageType.Builder, com.wisekrakr.wisesecurecomm.communication.proto.MessageTypeOrBuilder> messageTypeBuilder_;
    /**
     * <code>.com.wisekrakr.wisesecurecomm.communication.proto.MessageType message_type = 3;</code>
     * @return Whether the messageType field is set.
     */
    public boolean hasMessageType() {
      return messageTypeBuilder_ != null || messageType_ != null;
    }
    /**
     * <code>.com.wisekrakr.wisesecurecomm.communication.proto.MessageType message_type = 3;</code>
     * @return The messageType.
     */
    public com.wisekrakr.wisesecurecomm.communication.proto.MessageType getMessageType() {
      if (messageTypeBuilder_ == null) {
        return messageType_ == null ? com.wisekrakr.wisesecurecomm.communication.proto.MessageType.getDefaultInstance() : messageType_;
      } else {
        return messageTypeBuilder_.getMessage();
      }
    }
    /**
     * <code>.com.wisekrakr.wisesecurecomm.communication.proto.MessageType message_type = 3;</code>
     */
    public Builder setMessageType(com.wisekrakr.wisesecurecomm.communication.proto.MessageType value) {
      if (messageTypeBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        messageType_ = value;
        onChanged();
      } else {
        messageTypeBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.com.wisekrakr.wisesecurecomm.communication.proto.MessageType message_type = 3;</code>
     */
    public Builder setMessageType(
        com.wisekrakr.wisesecurecomm.communication.proto.MessageType.Builder builderForValue) {
      if (messageTypeBuilder_ == null) {
        messageType_ = builderForValue.build();
        onChanged();
      } else {
        messageTypeBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.com.wisekrakr.wisesecurecomm.communication.proto.MessageType message_type = 3;</code>
     */
    public Builder mergeMessageType(com.wisekrakr.wisesecurecomm.communication.proto.MessageType value) {
      if (messageTypeBuilder_ == null) {
        if (messageType_ != null) {
          messageType_ =
            com.wisekrakr.wisesecurecomm.communication.proto.MessageType.newBuilder(messageType_).mergeFrom(value).buildPartial();
        } else {
          messageType_ = value;
        }
        onChanged();
      } else {
        messageTypeBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.com.wisekrakr.wisesecurecomm.communication.proto.MessageType message_type = 3;</code>
     */
    public Builder clearMessageType() {
      if (messageTypeBuilder_ == null) {
        messageType_ = null;
        onChanged();
      } else {
        messageType_ = null;
        messageTypeBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.com.wisekrakr.wisesecurecomm.communication.proto.MessageType message_type = 3;</code>
     */
    public com.wisekrakr.wisesecurecomm.communication.proto.MessageType.Builder getMessageTypeBuilder() {
      
      onChanged();
      return getMessageTypeFieldBuilder().getBuilder();
    }
    /**
     * <code>.com.wisekrakr.wisesecurecomm.communication.proto.MessageType message_type = 3;</code>
     */
    public com.wisekrakr.wisesecurecomm.communication.proto.MessageTypeOrBuilder getMessageTypeOrBuilder() {
      if (messageTypeBuilder_ != null) {
        return messageTypeBuilder_.getMessageOrBuilder();
      } else {
        return messageType_ == null ?
            com.wisekrakr.wisesecurecomm.communication.proto.MessageType.getDefaultInstance() : messageType_;
      }
    }
    /**
     * <code>.com.wisekrakr.wisesecurecomm.communication.proto.MessageType message_type = 3;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.wisekrakr.wisesecurecomm.communication.proto.MessageType, com.wisekrakr.wisesecurecomm.communication.proto.MessageType.Builder, com.wisekrakr.wisesecurecomm.communication.proto.MessageTypeOrBuilder> 
        getMessageTypeFieldBuilder() {
      if (messageTypeBuilder_ == null) {
        messageTypeBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.wisekrakr.wisesecurecomm.communication.proto.MessageType, com.wisekrakr.wisesecurecomm.communication.proto.MessageType.Builder, com.wisekrakr.wisesecurecomm.communication.proto.MessageTypeOrBuilder>(
                getMessageType(),
                getParentForChildren(),
                isClean());
        messageType_ = null;
      }
      return messageTypeBuilder_;
    }

    private java.lang.Object textMessage_ = "";
    /**
     * <code>string text_message = 4;</code>
     * @return The textMessage.
     */
    public java.lang.String getTextMessage() {
      java.lang.Object ref = textMessage_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        textMessage_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string text_message = 4;</code>
     * @return The bytes for textMessage.
     */
    public com.google.protobuf.ByteString
        getTextMessageBytes() {
      java.lang.Object ref = textMessage_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        textMessage_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string text_message = 4;</code>
     * @param value The textMessage to set.
     * @return This builder for chaining.
     */
    public Builder setTextMessage(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      textMessage_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string text_message = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearTextMessage() {
      
      textMessage_ = getDefaultInstance().getTextMessage();
      onChanged();
      return this;
    }
    /**
     * <code>string text_message = 4;</code>
     * @param value The bytes for textMessage to set.
     * @return This builder for chaining.
     */
    public Builder setTextMessageBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      textMessage_ = value;
      onChanged();
      return this;
    }

    private com.google.protobuf.ByteString voiceMessage_ = com.google.protobuf.ByteString.EMPTY;
    /**
     * <code>bytes voice_message = 5;</code>
     * @return The voiceMessage.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getVoiceMessage() {
      return voiceMessage_;
    }
    /**
     * <code>bytes voice_message = 5;</code>
     * @param value The voiceMessage to set.
     * @return This builder for chaining.
     */
    public Builder setVoiceMessage(com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      voiceMessage_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>bytes voice_message = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearVoiceMessage() {
      
      voiceMessage_ = getDefaultInstance().getVoiceMessage();
      onChanged();
      return this;
    }

    private com.wisekrakr.wisesecurecomm.communication.proto.FileInfo fileInfo_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.wisekrakr.wisesecurecomm.communication.proto.FileInfo, com.wisekrakr.wisesecurecomm.communication.proto.FileInfo.Builder, com.wisekrakr.wisesecurecomm.communication.proto.FileInfoOrBuilder> fileInfoBuilder_;
    /**
     * <code>.com.wisekrakr.wisesecurecomm.communication.proto.FileInfo file_info = 6;</code>
     * @return Whether the fileInfo field is set.
     */
    public boolean hasFileInfo() {
      return fileInfoBuilder_ != null || fileInfo_ != null;
    }
    /**
     * <code>.com.wisekrakr.wisesecurecomm.communication.proto.FileInfo file_info = 6;</code>
     * @return The fileInfo.
     */
    public com.wisekrakr.wisesecurecomm.communication.proto.FileInfo getFileInfo() {
      if (fileInfoBuilder_ == null) {
        return fileInfo_ == null ? com.wisekrakr.wisesecurecomm.communication.proto.FileInfo.getDefaultInstance() : fileInfo_;
      } else {
        return fileInfoBuilder_.getMessage();
      }
    }
    /**
     * <code>.com.wisekrakr.wisesecurecomm.communication.proto.FileInfo file_info = 6;</code>
     */
    public Builder setFileInfo(com.wisekrakr.wisesecurecomm.communication.proto.FileInfo value) {
      if (fileInfoBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        fileInfo_ = value;
        onChanged();
      } else {
        fileInfoBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.com.wisekrakr.wisesecurecomm.communication.proto.FileInfo file_info = 6;</code>
     */
    public Builder setFileInfo(
        com.wisekrakr.wisesecurecomm.communication.proto.FileInfo.Builder builderForValue) {
      if (fileInfoBuilder_ == null) {
        fileInfo_ = builderForValue.build();
        onChanged();
      } else {
        fileInfoBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.com.wisekrakr.wisesecurecomm.communication.proto.FileInfo file_info = 6;</code>
     */
    public Builder mergeFileInfo(com.wisekrakr.wisesecurecomm.communication.proto.FileInfo value) {
      if (fileInfoBuilder_ == null) {
        if (fileInfo_ != null) {
          fileInfo_ =
            com.wisekrakr.wisesecurecomm.communication.proto.FileInfo.newBuilder(fileInfo_).mergeFrom(value).buildPartial();
        } else {
          fileInfo_ = value;
        }
        onChanged();
      } else {
        fileInfoBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.com.wisekrakr.wisesecurecomm.communication.proto.FileInfo file_info = 6;</code>
     */
    public Builder clearFileInfo() {
      if (fileInfoBuilder_ == null) {
        fileInfo_ = null;
        onChanged();
      } else {
        fileInfo_ = null;
        fileInfoBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.com.wisekrakr.wisesecurecomm.communication.proto.FileInfo file_info = 6;</code>
     */
    public com.wisekrakr.wisesecurecomm.communication.proto.FileInfo.Builder getFileInfoBuilder() {
      
      onChanged();
      return getFileInfoFieldBuilder().getBuilder();
    }
    /**
     * <code>.com.wisekrakr.wisesecurecomm.communication.proto.FileInfo file_info = 6;</code>
     */
    public com.wisekrakr.wisesecurecomm.communication.proto.FileInfoOrBuilder getFileInfoOrBuilder() {
      if (fileInfoBuilder_ != null) {
        return fileInfoBuilder_.getMessageOrBuilder();
      } else {
        return fileInfo_ == null ?
            com.wisekrakr.wisesecurecomm.communication.proto.FileInfo.getDefaultInstance() : fileInfo_;
      }
    }
    /**
     * <code>.com.wisekrakr.wisesecurecomm.communication.proto.FileInfo file_info = 6;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.wisekrakr.wisesecurecomm.communication.proto.FileInfo, com.wisekrakr.wisesecurecomm.communication.proto.FileInfo.Builder, com.wisekrakr.wisesecurecomm.communication.proto.FileInfoOrBuilder> 
        getFileInfoFieldBuilder() {
      if (fileInfoBuilder_ == null) {
        fileInfoBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.wisekrakr.wisesecurecomm.communication.proto.FileInfo, com.wisekrakr.wisesecurecomm.communication.proto.FileInfo.Builder, com.wisekrakr.wisesecurecomm.communication.proto.FileInfoOrBuilder>(
                getFileInfo(),
                getParentForChildren(),
                isClean());
        fileInfo_ = null;
      }
      return fileInfoBuilder_;
    }

    private long ownerId_ ;
    /**
     * <code>int64 owner_id = 7;</code>
     * @return The ownerId.
     */
    @java.lang.Override
    public long getOwnerId() {
      return ownerId_;
    }
    /**
     * <code>int64 owner_id = 7;</code>
     * @param value The ownerId to set.
     * @return This builder for chaining.
     */
    public Builder setOwnerId(long value) {
      
      ownerId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int64 owner_id = 7;</code>
     * @return This builder for chaining.
     */
    public Builder clearOwnerId() {
      
      ownerId_ = 0L;
      onChanged();
      return this;
    }

    private com.google.protobuf.Internal.LongList recipientsIds_ = emptyLongList();
    private void ensureRecipientsIdsIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        recipientsIds_ = mutableCopy(recipientsIds_);
        bitField0_ |= 0x00000001;
       }
    }
    /**
     * <code>repeated int64 recipients_ids = 8;</code>
     * @return A list containing the recipientsIds.
     */
    public java.util.List<java.lang.Long>
        getRecipientsIdsList() {
      return ((bitField0_ & 0x00000001) != 0) ?
               java.util.Collections.unmodifiableList(recipientsIds_) : recipientsIds_;
    }
    /**
     * <code>repeated int64 recipients_ids = 8;</code>
     * @return The count of recipientsIds.
     */
    public int getRecipientsIdsCount() {
      return recipientsIds_.size();
    }
    /**
     * <code>repeated int64 recipients_ids = 8;</code>
     * @param index The index of the element to return.
     * @return The recipientsIds at the given index.
     */
    public long getRecipientsIds(int index) {
      return recipientsIds_.getLong(index);
    }
    /**
     * <code>repeated int64 recipients_ids = 8;</code>
     * @param index The index to set the value at.
     * @param value The recipientsIds to set.
     * @return This builder for chaining.
     */
    public Builder setRecipientsIds(
        int index, long value) {
      ensureRecipientsIdsIsMutable();
      recipientsIds_.setLong(index, value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated int64 recipients_ids = 8;</code>
     * @param value The recipientsIds to add.
     * @return This builder for chaining.
     */
    public Builder addRecipientsIds(long value) {
      ensureRecipientsIdsIsMutable();
      recipientsIds_.addLong(value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated int64 recipients_ids = 8;</code>
     * @param values The recipientsIds to add.
     * @return This builder for chaining.
     */
    public Builder addAllRecipientsIds(
        java.lang.Iterable<? extends java.lang.Long> values) {
      ensureRecipientsIdsIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, recipientsIds_);
      onChanged();
      return this;
    }
    /**
     * <code>repeated int64 recipients_ids = 8;</code>
     * @return This builder for chaining.
     */
    public Builder clearRecipientsIds() {
      recipientsIds_ = emptyLongList();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:com.wisekrakr.wisesecurecomm.communication.proto.MessageObject)
  }

  // @@protoc_insertion_point(class_scope:com.wisekrakr.wisesecurecomm.communication.proto.MessageObject)
  private static final com.wisekrakr.wisesecurecomm.communication.proto.MessageObject DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.wisekrakr.wisesecurecomm.communication.proto.MessageObject();
  }

  public static com.wisekrakr.wisesecurecomm.communication.proto.MessageObject getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<MessageObject>
      PARSER = new com.google.protobuf.AbstractParser<MessageObject>() {
    @java.lang.Override
    public MessageObject parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new MessageObject(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<MessageObject> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<MessageObject> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.wisekrakr.wisesecurecomm.communication.proto.MessageObject getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

