// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: MessageObject.proto

package com.wisekrakr.wisesecurecomm.communication.proto;

public interface MessageObjectOrBuilder extends
    // @@protoc_insertion_point(interface_extends:MessageObject)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 id = 1;</code>
   * @return The id.
   */
  int getId();

  /**
   * <code>.MessageObject.ObjectType objectType = 2;</code>
   * @return The enum numeric value on the wire for objectType.
   */
  int getObjectTypeValue();
  /**
   * <code>.MessageObject.ObjectType objectType = 2;</code>
   * @return The objectType.
   */
  MessageObject.ObjectType getObjectType();

  /**
   * <code>.MessageType messageType = 3;</code>
   * @return Whether the messageType field is set.
   */
  boolean hasMessageType();
  /**
   * <code>.MessageType messageType = 3;</code>
   * @return The messageType.
   */
  MessageType getMessageType();
  /**
   * <code>.MessageType messageType = 3;</code>
   */
  MessageTypeOrBuilder getMessageTypeOrBuilder();

  /**
   * <code>string textMessage = 4;</code>
   * @return The textMessage.
   */
  String getTextMessage();
  /**
   * <code>string textMessage = 4;</code>
   * @return The bytes for textMessage.
   */
  com.google.protobuf.ByteString
      getTextMessageBytes();

  /**
   * <code>bytes voiceMessage = 5;</code>
   * @return The voiceMessage.
   */
  com.google.protobuf.ByteString getVoiceMessage();

  /**
   * <code>.FileInfo fileInfo = 6;</code>
   * @return Whether the fileInfo field is set.
   */
  boolean hasFileInfo();
  /**
   * <code>.FileInfo fileInfo = 6;</code>
   * @return The fileInfo.
   */
  FileInfo getFileInfo();
  /**
   * <code>.FileInfo fileInfo = 6;</code>
   */
  FileInfoOrBuilder getFileInfoOrBuilder();

  /**
   * <code>.User owner = 7;</code>
   * @return Whether the owner field is set.
   */
  boolean hasOwner();
  /**
   * <code>.User owner = 7;</code>
   * @return The owner.
   */
  User getOwner();
  /**
   * <code>.User owner = 7;</code>
   */
  UserOrBuilder getOwnerOrBuilder();

  /**
   * <code>repeated .User recipients = 8;</code>
   */
  java.util.List<User>
      getRecipientsList();
  /**
   * <code>repeated .User recipients = 8;</code>
   */
  User getRecipients(int index);
  /**
   * <code>repeated .User recipients = 8;</code>
   */
  int getRecipientsCount();
  /**
   * <code>repeated .User recipients = 8;</code>
   */
  java.util.List<? extends UserOrBuilder>
      getRecipientsOrBuilderList();
  /**
   * <code>repeated .User recipients = 8;</code>
   */
  UserOrBuilder getRecipientsOrBuilder(
      int index);
}
