// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: MessageObject.proto

package com.wisekrakr.wisesecurecomm.communication.proto;

/**
 * Protobuf type {@code MessageObject}
 */
public final class MessageObject extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:MessageObject)
    MessageObjectOrBuilder {
private static final long serialVersionUID = 0L;
  // Use MessageObject.newBuilder() to construct.
  private MessageObject(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private MessageObject() {
    objectType_ = 0;
    textMessage_ = "";
    voiceMessage_ = com.google.protobuf.ByteString.EMPTY;
    recipients_ = java.util.Collections.emptyList();
  }

  @Override
  @SuppressWarnings({"unused"})
  protected Object newInstance(
      UnusedPrivateParameter unused) {
    return new MessageObject();
  }

  @Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private MessageObject(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {

            id_ = input.readInt32();
            break;
          }
          case 16: {
            int rawValue = input.readEnum();

            objectType_ = rawValue;
            break;
          }
          case 26: {
            MessageType.Builder subBuilder = null;
            if (messageType_ != null) {
              subBuilder = messageType_.toBuilder();
            }
            messageType_ = input.readMessage(MessageType.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(messageType_);
              messageType_ = subBuilder.buildPartial();
            }

            break;
          }
          case 34: {
            String s = input.readStringRequireUtf8();

            textMessage_ = s;
            break;
          }
          case 42: {

            voiceMessage_ = input.readBytes();
            break;
          }
          case 50: {
            FileInfo.Builder subBuilder = null;
            if (fileInfo_ != null) {
              subBuilder = fileInfo_.toBuilder();
            }
            fileInfo_ = input.readMessage(FileInfo.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(fileInfo_);
              fileInfo_ = subBuilder.buildPartial();
            }

            break;
          }
          case 58: {
            User.Builder subBuilder = null;
            if (owner_ != null) {
              subBuilder = owner_.toBuilder();
            }
            owner_ = input.readMessage(User.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(owner_);
              owner_ = subBuilder.buildPartial();
            }

            break;
          }
          case 66: {
            if (!((mutable_bitField0_ & 0x00000001) != 0)) {
              recipients_ = new java.util.ArrayList<User>();
              mutable_bitField0_ |= 0x00000001;
            }
            recipients_.add(
                input.readMessage(User.parser(), extensionRegistry));
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) != 0)) {
        recipients_ = java.util.Collections.unmodifiableList(recipients_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return MessageObjectOuterClass.internal_static_server_src_com_wisekrakr_wisesecurecomm_communication_MessageObject_descriptor;
  }

  @Override
  protected FieldAccessorTable
      internalGetFieldAccessorTable() {
    return MessageObjectOuterClass.internal_static_server_src_com_wisekrakr_wisesecurecomm_communication_MessageObject_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            MessageObject.class, Builder.class);
  }

  /**
   * Protobuf enum {@code MessageObject.ObjectType}
   */
  public enum ObjectType
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>MESSAGE = 0;</code>
     */
    MESSAGE(0),
    /**
     * <code>NOTIFICATION = 1;</code>
     */
    NOTIFICATION(1),
    /**
     * <code>COMMAND = 2;</code>
     */
    COMMAND(2),
    /**
     * <code>SECURITY = 3;</code>
     */
    SECURITY(3),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>MESSAGE = 0;</code>
     */
    public static final int MESSAGE_VALUE = 0;
    /**
     * <code>NOTIFICATION = 1;</code>
     */
    public static final int NOTIFICATION_VALUE = 1;
    /**
     * <code>COMMAND = 2;</code>
     */
    public static final int COMMAND_VALUE = 2;
    /**
     * <code>SECURITY = 3;</code>
     */
    public static final int SECURITY_VALUE = 3;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @Deprecated
    public static ObjectType valueOf(int value) {
      return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static ObjectType forNumber(int value) {
      switch (value) {
        case 0: return MESSAGE;
        case 1: return NOTIFICATION;
        case 2: return COMMAND;
        case 3: return SECURITY;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<ObjectType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        ObjectType> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<ObjectType>() {
            public ObjectType findValueByNumber(int number) {
              return ObjectType.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      if (this == UNRECOGNIZED) {
        throw new IllegalStateException(
            "Can't get the descriptor of an unrecognized enum value.");
      }
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return MessageObject.getDescriptor().getEnumTypes().get(0);
    }

    private static final ObjectType[] VALUES = values();

    public static ObjectType valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private ObjectType(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:MessageObject.ObjectType)
  }

  public static final int ID_FIELD_NUMBER = 1;
  private int id_;
  /**
   * <code>int32 id = 1;</code>
   * @return The id.
   */
  @Override
  public int getId() {
    return id_;
  }

  public static final int OBJECTTYPE_FIELD_NUMBER = 2;
  private int objectType_;
  /**
   * <code>.MessageObject.ObjectType objectType = 2;</code>
   * @return The enum numeric value on the wire for objectType.
   */
  @Override public int getObjectTypeValue() {
    return objectType_;
  }
  /**
   * <code>.MessageObject.ObjectType objectType = 2;</code>
   * @return The objectType.
   */
  @Override public ObjectType getObjectType() {
    @SuppressWarnings("deprecation")
    ObjectType result = ObjectType.valueOf(objectType_);
    return result == null ? ObjectType.UNRECOGNIZED : result;
  }

  public static final int MESSAGETYPE_FIELD_NUMBER = 3;
  private MessageType messageType_;
  /**
   * <code>.MessageType messageType = 3;</code>
   * @return Whether the messageType field is set.
   */
  @Override
  public boolean hasMessageType() {
    return messageType_ != null;
  }
  /**
   * <code>.MessageType messageType = 3;</code>
   * @return The messageType.
   */
  @Override
  public MessageType getMessageType() {
    return messageType_ == null ? MessageType.getDefaultInstance() : messageType_;
  }
  /**
   * <code>.MessageType messageType = 3;</code>
   */
  @Override
  public MessageTypeOrBuilder getMessageTypeOrBuilder() {
    return getMessageType();
  }

  public static final int TEXTMESSAGE_FIELD_NUMBER = 4;
  private volatile Object textMessage_;
  /**
   * <code>string textMessage = 4;</code>
   * @return The textMessage.
   */
  @Override
  public String getTextMessage() {
    Object ref = textMessage_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs =
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      textMessage_ = s;
      return s;
    }
  }
  /**
   * <code>string textMessage = 4;</code>
   * @return The bytes for textMessage.
   */
  @Override
  public com.google.protobuf.ByteString
      getTextMessageBytes() {
    Object ref = textMessage_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b =
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      textMessage_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int VOICEMESSAGE_FIELD_NUMBER = 5;
  private com.google.protobuf.ByteString voiceMessage_;
  /**
   * <code>bytes voiceMessage = 5;</code>
   * @return The voiceMessage.
   */
  @Override
  public com.google.protobuf.ByteString getVoiceMessage() {
    return voiceMessage_;
  }

  public static final int FILEINFO_FIELD_NUMBER = 6;
  private FileInfo fileInfo_;
  /**
   * <code>.FileInfo fileInfo = 6;</code>
   * @return Whether the fileInfo field is set.
   */
  @Override
  public boolean hasFileInfo() {
    return fileInfo_ != null;
  }
  /**
   * <code>.FileInfo fileInfo = 6;</code>
   * @return The fileInfo.
   */
  @Override
  public FileInfo getFileInfo() {
    return fileInfo_ == null ? FileInfo.getDefaultInstance() : fileInfo_;
  }
  /**
   * <code>.FileInfo fileInfo = 6;</code>
   */
  @Override
  public FileInfoOrBuilder getFileInfoOrBuilder() {
    return getFileInfo();
  }

  public static final int OWNER_FIELD_NUMBER = 7;
  private User owner_;
  /**
   * <code>.User owner = 7;</code>
   * @return Whether the owner field is set.
   */
  @Override
  public boolean hasOwner() {
    return owner_ != null;
  }
  /**
   * <code>.User owner = 7;</code>
   * @return The owner.
   */
  @Override
  public User getOwner() {
    return owner_ == null ? User.getDefaultInstance() : owner_;
  }
  /**
   * <code>.User owner = 7;</code>
   */
  @Override
  public UserOrBuilder getOwnerOrBuilder() {
    return getOwner();
  }

  public static final int RECIPIENTS_FIELD_NUMBER = 8;
  private java.util.List<User> recipients_;
  /**
   * <code>repeated .User recipients = 8;</code>
   */
  @Override
  public java.util.List<User> getRecipientsList() {
    return recipients_;
  }
  /**
   * <code>repeated .User recipients = 8;</code>
   */
  @Override
  public java.util.List<? extends UserOrBuilder>
      getRecipientsOrBuilderList() {
    return recipients_;
  }
  /**
   * <code>repeated .User recipients = 8;</code>
   */
  @Override
  public int getRecipientsCount() {
    return recipients_.size();
  }
  /**
   * <code>repeated .User recipients = 8;</code>
   */
  @Override
  public User getRecipients(int index) {
    return recipients_.get(index);
  }
  /**
   * <code>repeated .User recipients = 8;</code>
   */
  @Override
  public UserOrBuilder getRecipientsOrBuilder(
      int index) {
    return recipients_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (id_ != 0) {
      output.writeInt32(1, id_);
    }
    if (objectType_ != ObjectType.MESSAGE.getNumber()) {
      output.writeEnum(2, objectType_);
    }
    if (messageType_ != null) {
      output.writeMessage(3, getMessageType());
    }
    if (!getTextMessageBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, textMessage_);
    }
    if (!voiceMessage_.isEmpty()) {
      output.writeBytes(5, voiceMessage_);
    }
    if (fileInfo_ != null) {
      output.writeMessage(6, getFileInfo());
    }
    if (owner_ != null) {
      output.writeMessage(7, getOwner());
    }
    for (int i = 0; i < recipients_.size(); i++) {
      output.writeMessage(8, recipients_.get(i));
    }
    unknownFields.writeTo(output);
  }

  @Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (id_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(1, id_);
    }
    if (objectType_ != ObjectType.MESSAGE.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(2, objectType_);
    }
    if (messageType_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, getMessageType());
    }
    if (!getTextMessageBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, textMessage_);
    }
    if (!voiceMessage_.isEmpty()) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(5, voiceMessage_);
    }
    if (fileInfo_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(6, getFileInfo());
    }
    if (owner_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(7, getOwner());
    }
    for (int i = 0; i < recipients_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(8, recipients_.get(i));
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @Override
  public boolean equals(final Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof MessageObject)) {
      return super.equals(obj);
    }
    MessageObject other = (MessageObject) obj;

    if (getId()
        != other.getId()) return false;
    if (objectType_ != other.objectType_) return false;
    if (hasMessageType() != other.hasMessageType()) return false;
    if (hasMessageType()) {
      if (!getMessageType()
          .equals(other.getMessageType())) return false;
    }
    if (!getTextMessage()
        .equals(other.getTextMessage())) return false;
    if (!getVoiceMessage()
        .equals(other.getVoiceMessage())) return false;
    if (hasFileInfo() != other.hasFileInfo()) return false;
    if (hasFileInfo()) {
      if (!getFileInfo()
          .equals(other.getFileInfo())) return false;
    }
    if (hasOwner() != other.hasOwner()) return false;
    if (hasOwner()) {
      if (!getOwner()
          .equals(other.getOwner())) return false;
    }
    if (!getRecipientsList()
        .equals(other.getRecipientsList())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + ID_FIELD_NUMBER;
    hash = (53 * hash) + getId();
    hash = (37 * hash) + OBJECTTYPE_FIELD_NUMBER;
    hash = (53 * hash) + objectType_;
    if (hasMessageType()) {
      hash = (37 * hash) + MESSAGETYPE_FIELD_NUMBER;
      hash = (53 * hash) + getMessageType().hashCode();
    }
    hash = (37 * hash) + TEXTMESSAGE_FIELD_NUMBER;
    hash = (53 * hash) + getTextMessage().hashCode();
    hash = (37 * hash) + VOICEMESSAGE_FIELD_NUMBER;
    hash = (53 * hash) + getVoiceMessage().hashCode();
    if (hasFileInfo()) {
      hash = (37 * hash) + FILEINFO_FIELD_NUMBER;
      hash = (53 * hash) + getFileInfo().hashCode();
    }
    if (hasOwner()) {
      hash = (37 * hash) + OWNER_FIELD_NUMBER;
      hash = (53 * hash) + getOwner().hashCode();
    }
    if (getRecipientsCount() > 0) {
      hash = (37 * hash) + RECIPIENTS_FIELD_NUMBER;
      hash = (53 * hash) + getRecipientsList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static MessageObject parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static MessageObject parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static MessageObject parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static MessageObject parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static MessageObject parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static MessageObject parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static MessageObject parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static MessageObject parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static MessageObject parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static MessageObject parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static MessageObject parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static MessageObject parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(MessageObject prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @Override
  protected Builder newBuilderForType(
      BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code MessageObject}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:MessageObject)
          MessageObjectOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return MessageObjectOuterClass.internal_static_server_src_com_wisekrakr_wisesecurecomm_communication_MessageObject_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return MessageObjectOuterClass.internal_static_server_src_com_wisekrakr_wisesecurecomm_communication_MessageObject_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              MessageObject.class, Builder.class);
    }

    // Construct using MessageObject.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getRecipientsFieldBuilder();
      }
    }
    @Override
    public Builder clear() {
      super.clear();
      id_ = 0;

      objectType_ = 0;

      if (messageTypeBuilder_ == null) {
        messageType_ = null;
      } else {
        messageType_ = null;
        messageTypeBuilder_ = null;
      }
      textMessage_ = "";

      voiceMessage_ = com.google.protobuf.ByteString.EMPTY;

      if (fileInfoBuilder_ == null) {
        fileInfo_ = null;
      } else {
        fileInfo_ = null;
        fileInfoBuilder_ = null;
      }
      if (ownerBuilder_ == null) {
        owner_ = null;
      } else {
        owner_ = null;
        ownerBuilder_ = null;
      }
      if (recipientsBuilder_ == null) {
        recipients_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
      } else {
        recipientsBuilder_.clear();
      }
      return this;
    }

    @Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return MessageObjectOuterClass.internal_static_server_src_com_wisekrakr_wisesecurecomm_communication_MessageObject_descriptor;
    }

    @Override
    public MessageObject getDefaultInstanceForType() {
      return MessageObject.getDefaultInstance();
    }

    @Override
    public MessageObject build() {
      MessageObject result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @Override
    public MessageObject buildPartial() {
      MessageObject result = new MessageObject(this);
      int from_bitField0_ = bitField0_;
      result.id_ = id_;
      result.objectType_ = objectType_;
      if (messageTypeBuilder_ == null) {
        result.messageType_ = messageType_;
      } else {
        result.messageType_ = messageTypeBuilder_.build();
      }
      result.textMessage_ = textMessage_;
      result.voiceMessage_ = voiceMessage_;
      if (fileInfoBuilder_ == null) {
        result.fileInfo_ = fileInfo_;
      } else {
        result.fileInfo_ = fileInfoBuilder_.build();
      }
      if (ownerBuilder_ == null) {
        result.owner_ = owner_;
      } else {
        result.owner_ = ownerBuilder_.build();
      }
      if (recipientsBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          recipients_ = java.util.Collections.unmodifiableList(recipients_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.recipients_ = recipients_;
      } else {
        result.recipients_ = recipientsBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @Override
    public Builder clone() {
      return super.clone();
    }
    @Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return super.setField(field, value);
    }
    @Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return super.addRepeatedField(field, value);
    }
    @Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof MessageObject) {
        return mergeFrom((MessageObject)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(MessageObject other) {
      if (other == MessageObject.getDefaultInstance()) return this;
      if (other.getId() != 0) {
        setId(other.getId());
      }
      if (other.objectType_ != 0) {
        setObjectTypeValue(other.getObjectTypeValue());
      }
      if (other.hasMessageType()) {
        mergeMessageType(other.getMessageType());
      }
      if (!other.getTextMessage().isEmpty()) {
        textMessage_ = other.textMessage_;
        onChanged();
      }
      if (other.getVoiceMessage() != com.google.protobuf.ByteString.EMPTY) {
        setVoiceMessage(other.getVoiceMessage());
      }
      if (other.hasFileInfo()) {
        mergeFileInfo(other.getFileInfo());
      }
      if (other.hasOwner()) {
        mergeOwner(other.getOwner());
      }
      if (recipientsBuilder_ == null) {
        if (!other.recipients_.isEmpty()) {
          if (recipients_.isEmpty()) {
            recipients_ = other.recipients_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureRecipientsIsMutable();
            recipients_.addAll(other.recipients_);
          }
          onChanged();
        }
      } else {
        if (!other.recipients_.isEmpty()) {
          if (recipientsBuilder_.isEmpty()) {
            recipientsBuilder_.dispose();
            recipientsBuilder_ = null;
            recipients_ = other.recipients_;
            bitField0_ = (bitField0_ & ~0x00000001);
            recipientsBuilder_ =
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getRecipientsFieldBuilder() : null;
          } else {
            recipientsBuilder_.addAllMessages(other.recipients_);
          }
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @Override
    public final boolean isInitialized() {
      return true;
    }

    @Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      MessageObject parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (MessageObject) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private int id_ ;
    /**
     * <code>int32 id = 1;</code>
     * @return The id.
     */
    @Override
    public int getId() {
      return id_;
    }
    /**
     * <code>int32 id = 1;</code>
     * @param value The id to set.
     * @return This builder for chaining.
     */
    public Builder setId(int value) {

      id_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 id = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearId() {

      id_ = 0;
      onChanged();
      return this;
    }

    private int objectType_ = 0;
    /**
     * <code>.MessageObject.ObjectType objectType = 2;</code>
     * @return The enum numeric value on the wire for objectType.
     */
    @Override public int getObjectTypeValue() {
      return objectType_;
    }
    /**
     * <code>.MessageObject.ObjectType objectType = 2;</code>
     * @param value The enum numeric value on the wire for objectType to set.
     * @return This builder for chaining.
     */
    public Builder setObjectTypeValue(int value) {

      objectType_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>.MessageObject.ObjectType objectType = 2;</code>
     * @return The objectType.
     */
    @Override
    public ObjectType getObjectType() {
      @SuppressWarnings("deprecation")
      ObjectType result = ObjectType.valueOf(objectType_);
      return result == null ? ObjectType.UNRECOGNIZED : result;
    }
    /**
     * <code>.MessageObject.ObjectType objectType = 2;</code>
     * @param value The objectType to set.
     * @return This builder for chaining.
     */
    public Builder setObjectType(ObjectType value) {
      if (value == null) {
        throw new NullPointerException();
      }

      objectType_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>.MessageObject.ObjectType objectType = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearObjectType() {

      objectType_ = 0;
      onChanged();
      return this;
    }

    private MessageType messageType_;
    private com.google.protobuf.SingleFieldBuilderV3<
            MessageType, MessageType.Builder, MessageTypeOrBuilder> messageTypeBuilder_;
    /**
     * <code>.MessageType messageType = 3;</code>
     * @return Whether the messageType field is set.
     */
    public boolean hasMessageType() {
      return messageTypeBuilder_ != null || messageType_ != null;
    }
    /**
     * <code>.MessageType messageType = 3;</code>
     * @return The messageType.
     */
    public MessageType getMessageType() {
      if (messageTypeBuilder_ == null) {
        return messageType_ == null ? MessageType.getDefaultInstance() : messageType_;
      } else {
        return messageTypeBuilder_.getMessage();
      }
    }
    /**
     * <code>.MessageType messageType = 3;</code>
     */
    public Builder setMessageType(MessageType value) {
      if (messageTypeBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        messageType_ = value;
        onChanged();
      } else {
        messageTypeBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.MessageType messageType = 3;</code>
     */
    public Builder setMessageType(
        MessageType.Builder builderForValue) {
      if (messageTypeBuilder_ == null) {
        messageType_ = builderForValue.build();
        onChanged();
      } else {
        messageTypeBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.MessageType messageType = 3;</code>
     */
    public Builder mergeMessageType(MessageType value) {
      if (messageTypeBuilder_ == null) {
        if (messageType_ != null) {
          messageType_ =
            MessageType.newBuilder(messageType_).mergeFrom(value).buildPartial();
        } else {
          messageType_ = value;
        }
        onChanged();
      } else {
        messageTypeBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.MessageType messageType = 3;</code>
     */
    public Builder clearMessageType() {
      if (messageTypeBuilder_ == null) {
        messageType_ = null;
        onChanged();
      } else {
        messageType_ = null;
        messageTypeBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.MessageType messageType = 3;</code>
     */
    public MessageType.Builder getMessageTypeBuilder() {

      onChanged();
      return getMessageTypeFieldBuilder().getBuilder();
    }
    /**
     * <code>.MessageType messageType = 3;</code>
     */
    public MessageTypeOrBuilder getMessageTypeOrBuilder() {
      if (messageTypeBuilder_ != null) {
        return messageTypeBuilder_.getMessageOrBuilder();
      } else {
        return messageType_ == null ?
            MessageType.getDefaultInstance() : messageType_;
      }
    }
    /**
     * <code>.MessageType messageType = 3;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
            MessageType, MessageType.Builder, MessageTypeOrBuilder>
        getMessageTypeFieldBuilder() {
      if (messageTypeBuilder_ == null) {
        messageTypeBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
                MessageType, MessageType.Builder, MessageTypeOrBuilder>(
                getMessageType(),
                getParentForChildren(),
                isClean());
        messageType_ = null;
      }
      return messageTypeBuilder_;
    }

    private Object textMessage_ = "";
    /**
     * <code>string textMessage = 4;</code>
     * @return The textMessage.
     */
    public String getTextMessage() {
      Object ref = textMessage_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        textMessage_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <code>string textMessage = 4;</code>
     * @return The bytes for textMessage.
     */
    public com.google.protobuf.ByteString
        getTextMessageBytes() {
      Object ref = textMessage_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        textMessage_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string textMessage = 4;</code>
     * @param value The textMessage to set.
     * @return This builder for chaining.
     */
    public Builder setTextMessage(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }

      textMessage_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string textMessage = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearTextMessage() {

      textMessage_ = getDefaultInstance().getTextMessage();
      onChanged();
      return this;
    }
    /**
     * <code>string textMessage = 4;</code>
     * @param value The bytes for textMessage to set.
     * @return This builder for chaining.
     */
    public Builder setTextMessageBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);

      textMessage_ = value;
      onChanged();
      return this;
    }

    private com.google.protobuf.ByteString voiceMessage_ = com.google.protobuf.ByteString.EMPTY;
    /**
     * <code>bytes voiceMessage = 5;</code>
     * @return The voiceMessage.
     */
    @Override
    public com.google.protobuf.ByteString getVoiceMessage() {
      return voiceMessage_;
    }
    /**
     * <code>bytes voiceMessage = 5;</code>
     * @param value The voiceMessage to set.
     * @return This builder for chaining.
     */
    public Builder setVoiceMessage(com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }

      voiceMessage_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>bytes voiceMessage = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearVoiceMessage() {

      voiceMessage_ = getDefaultInstance().getVoiceMessage();
      onChanged();
      return this;
    }

    private FileInfo fileInfo_;
    private com.google.protobuf.SingleFieldBuilderV3<
            FileInfo, FileInfo.Builder, FileInfoOrBuilder> fileInfoBuilder_;
    /**
     * <code>.FileInfo fileInfo = 6;</code>
     * @return Whether the fileInfo field is set.
     */
    public boolean hasFileInfo() {
      return fileInfoBuilder_ != null || fileInfo_ != null;
    }
    /**
     * <code>.FileInfo fileInfo = 6;</code>
     * @return The fileInfo.
     */
    public FileInfo getFileInfo() {
      if (fileInfoBuilder_ == null) {
        return fileInfo_ == null ? FileInfo.getDefaultInstance() : fileInfo_;
      } else {
        return fileInfoBuilder_.getMessage();
      }
    }
    /**
     * <code>.FileInfo fileInfo = 6;</code>
     */
    public Builder setFileInfo(FileInfo value) {
      if (fileInfoBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        fileInfo_ = value;
        onChanged();
      } else {
        fileInfoBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.FileInfo fileInfo = 6;</code>
     */
    public Builder setFileInfo(
        FileInfo.Builder builderForValue) {
      if (fileInfoBuilder_ == null) {
        fileInfo_ = builderForValue.build();
        onChanged();
      } else {
        fileInfoBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.FileInfo fileInfo = 6;</code>
     */
    public Builder mergeFileInfo(FileInfo value) {
      if (fileInfoBuilder_ == null) {
        if (fileInfo_ != null) {
          fileInfo_ =
            FileInfo.newBuilder(fileInfo_).mergeFrom(value).buildPartial();
        } else {
          fileInfo_ = value;
        }
        onChanged();
      } else {
        fileInfoBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.FileInfo fileInfo = 6;</code>
     */
    public Builder clearFileInfo() {
      if (fileInfoBuilder_ == null) {
        fileInfo_ = null;
        onChanged();
      } else {
        fileInfo_ = null;
        fileInfoBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.FileInfo fileInfo = 6;</code>
     */
    public FileInfo.Builder getFileInfoBuilder() {

      onChanged();
      return getFileInfoFieldBuilder().getBuilder();
    }
    /**
     * <code>.FileInfo fileInfo = 6;</code>
     */
    public FileInfoOrBuilder getFileInfoOrBuilder() {
      if (fileInfoBuilder_ != null) {
        return fileInfoBuilder_.getMessageOrBuilder();
      } else {
        return fileInfo_ == null ?
            FileInfo.getDefaultInstance() : fileInfo_;
      }
    }
    /**
     * <code>.FileInfo fileInfo = 6;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
            FileInfo, FileInfo.Builder, FileInfoOrBuilder>
        getFileInfoFieldBuilder() {
      if (fileInfoBuilder_ == null) {
        fileInfoBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
                FileInfo, FileInfo.Builder, FileInfoOrBuilder>(
                getFileInfo(),
                getParentForChildren(),
                isClean());
        fileInfo_ = null;
      }
      return fileInfoBuilder_;
    }

    private User owner_;
    private com.google.protobuf.SingleFieldBuilderV3<
            User, User.Builder, UserOrBuilder> ownerBuilder_;
    /**
     * <code>.User owner = 7;</code>
     * @return Whether the owner field is set.
     */
    public boolean hasOwner() {
      return ownerBuilder_ != null || owner_ != null;
    }
    /**
     * <code>.User owner = 7;</code>
     * @return The owner.
     */
    public User getOwner() {
      if (ownerBuilder_ == null) {
        return owner_ == null ? User.getDefaultInstance() : owner_;
      } else {
        return ownerBuilder_.getMessage();
      }
    }
    /**
     * <code>.User owner = 7;</code>
     */
    public Builder setOwner(User value) {
      if (ownerBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        owner_ = value;
        onChanged();
      } else {
        ownerBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.User owner = 7;</code>
     */
    public Builder setOwner(
        User.Builder builderForValue) {
      if (ownerBuilder_ == null) {
        owner_ = builderForValue.build();
        onChanged();
      } else {
        ownerBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.User owner = 7;</code>
     */
    public Builder mergeOwner(User value) {
      if (ownerBuilder_ == null) {
        if (owner_ != null) {
          owner_ =
            User.newBuilder(owner_).mergeFrom(value).buildPartial();
        } else {
          owner_ = value;
        }
        onChanged();
      } else {
        ownerBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.User owner = 7;</code>
     */
    public Builder clearOwner() {
      if (ownerBuilder_ == null) {
        owner_ = null;
        onChanged();
      } else {
        owner_ = null;
        ownerBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.User owner = 7;</code>
     */
    public User.Builder getOwnerBuilder() {

      onChanged();
      return getOwnerFieldBuilder().getBuilder();
    }
    /**
     * <code>.User owner = 7;</code>
     */
    public UserOrBuilder getOwnerOrBuilder() {
      if (ownerBuilder_ != null) {
        return ownerBuilder_.getMessageOrBuilder();
      } else {
        return owner_ == null ?
            User.getDefaultInstance() : owner_;
      }
    }
    /**
     * <code>.User owner = 7;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
            User, User.Builder, UserOrBuilder>
        getOwnerFieldBuilder() {
      if (ownerBuilder_ == null) {
        ownerBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
                User, User.Builder, UserOrBuilder>(
                getOwner(),
                getParentForChildren(),
                isClean());
        owner_ = null;
      }
      return ownerBuilder_;
    }

    private java.util.List<User> recipients_ =
      java.util.Collections.emptyList();
    private void ensureRecipientsIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        recipients_ = new java.util.ArrayList<User>(recipients_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
            User, User.Builder, UserOrBuilder> recipientsBuilder_;

    /**
     * <code>repeated .User recipients = 8;</code>
     */
    public java.util.List<User> getRecipientsList() {
      if (recipientsBuilder_ == null) {
        return java.util.Collections.unmodifiableList(recipients_);
      } else {
        return recipientsBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .User recipients = 8;</code>
     */
    public int getRecipientsCount() {
      if (recipientsBuilder_ == null) {
        return recipients_.size();
      } else {
        return recipientsBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .User recipients = 8;</code>
     */
    public User getRecipients(int index) {
      if (recipientsBuilder_ == null) {
        return recipients_.get(index);
      } else {
        return recipientsBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .User recipients = 8;</code>
     */
    public Builder setRecipients(
        int index, User value) {
      if (recipientsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureRecipientsIsMutable();
        recipients_.set(index, value);
        onChanged();
      } else {
        recipientsBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .User recipients = 8;</code>
     */
    public Builder setRecipients(
        int index, User.Builder builderForValue) {
      if (recipientsBuilder_ == null) {
        ensureRecipientsIsMutable();
        recipients_.set(index, builderForValue.build());
        onChanged();
      } else {
        recipientsBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .User recipients = 8;</code>
     */
    public Builder addRecipients(User value) {
      if (recipientsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureRecipientsIsMutable();
        recipients_.add(value);
        onChanged();
      } else {
        recipientsBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .User recipients = 8;</code>
     */
    public Builder addRecipients(
        int index, User value) {
      if (recipientsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureRecipientsIsMutable();
        recipients_.add(index, value);
        onChanged();
      } else {
        recipientsBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .User recipients = 8;</code>
     */
    public Builder addRecipients(
        User.Builder builderForValue) {
      if (recipientsBuilder_ == null) {
        ensureRecipientsIsMutable();
        recipients_.add(builderForValue.build());
        onChanged();
      } else {
        recipientsBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .User recipients = 8;</code>
     */
    public Builder addRecipients(
        int index, User.Builder builderForValue) {
      if (recipientsBuilder_ == null) {
        ensureRecipientsIsMutable();
        recipients_.add(index, builderForValue.build());
        onChanged();
      } else {
        recipientsBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .User recipients = 8;</code>
     */
    public Builder addAllRecipients(
        Iterable<? extends User> values) {
      if (recipientsBuilder_ == null) {
        ensureRecipientsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, recipients_);
        onChanged();
      } else {
        recipientsBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .User recipients = 8;</code>
     */
    public Builder clearRecipients() {
      if (recipientsBuilder_ == null) {
        recipients_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        recipientsBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .User recipients = 8;</code>
     */
    public Builder removeRecipients(int index) {
      if (recipientsBuilder_ == null) {
        ensureRecipientsIsMutable();
        recipients_.remove(index);
        onChanged();
      } else {
        recipientsBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .User recipients = 8;</code>
     */
    public User.Builder getRecipientsBuilder(
        int index) {
      return getRecipientsFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .User recipients = 8;</code>
     */
    public UserOrBuilder getRecipientsOrBuilder(
        int index) {
      if (recipientsBuilder_ == null) {
        return recipients_.get(index);  } else {
        return recipientsBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .User recipients = 8;</code>
     */
    public java.util.List<? extends UserOrBuilder>
         getRecipientsOrBuilderList() {
      if (recipientsBuilder_ != null) {
        return recipientsBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(recipients_);
      }
    }
    /**
     * <code>repeated .User recipients = 8;</code>
     */
    public User.Builder addRecipientsBuilder() {
      return getRecipientsFieldBuilder().addBuilder(
          User.getDefaultInstance());
    }
    /**
     * <code>repeated .User recipients = 8;</code>
     */
    public User.Builder addRecipientsBuilder(
        int index) {
      return getRecipientsFieldBuilder().addBuilder(
          index, User.getDefaultInstance());
    }
    /**
     * <code>repeated .User recipients = 8;</code>
     */
    public java.util.List<User.Builder>
         getRecipientsBuilderList() {
      return getRecipientsFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
            User, User.Builder, UserOrBuilder>
        getRecipientsFieldBuilder() {
      if (recipientsBuilder_ == null) {
        recipientsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
                User, User.Builder, UserOrBuilder>(
                recipients_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        recipients_ = null;
      }
      return recipientsBuilder_;
    }
    @Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:MessageObject)
  }

  // @@protoc_insertion_point(class_scope:MessageObject)
  private static final MessageObject DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new MessageObject();
  }

  public static MessageObject getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<MessageObject>
      PARSER = new com.google.protobuf.AbstractParser<MessageObject>() {
    @Override
    public MessageObject parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new MessageObject(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<MessageObject> parser() {
    return PARSER;
  }

  @Override
  public com.google.protobuf.Parser<MessageObject> getParserForType() {
    return PARSER;
  }

  @Override
  public MessageObject getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

