// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: MessageObject.proto

package com.wisekrakr.wisesecurecomm.communication.proto;

public interface MessageTypeOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.wisekrakr.wisesecurecomm.communication.proto.MessageType)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.com.wisekrakr.wisesecurecomm.communication.proto.MessageType.Message message = 1;</code>
   * @return The enum numeric value on the wire for message.
   */
  int getMessageValue();
  /**
   * <code>.com.wisekrakr.wisesecurecomm.communication.proto.MessageType.Message message = 1;</code>
   * @return The message.
   */
  com.wisekrakr.wisesecurecomm.communication.proto.MessageType.Message getMessage();

  /**
   * <code>.com.wisekrakr.wisesecurecomm.communication.proto.MessageType.Notifications notifications = 2;</code>
   * @return The enum numeric value on the wire for notifications.
   */
  int getNotificationsValue();
  /**
   * <code>.com.wisekrakr.wisesecurecomm.communication.proto.MessageType.Notifications notifications = 2;</code>
   * @return The notifications.
   */
  com.wisekrakr.wisesecurecomm.communication.proto.MessageType.Notifications getNotifications();

  /**
   * <code>.com.wisekrakr.wisesecurecomm.communication.proto.MessageType.Commands commands = 3;</code>
   * @return The enum numeric value on the wire for commands.
   */
  int getCommandsValue();
  /**
   * <code>.com.wisekrakr.wisesecurecomm.communication.proto.MessageType.Commands commands = 3;</code>
   * @return The commands.
   */
  com.wisekrakr.wisesecurecomm.communication.proto.MessageType.Commands getCommands();

  /**
   * <code>.com.wisekrakr.wisesecurecomm.communication.proto.MessageType.Security security = 4;</code>
   * @return The enum numeric value on the wire for security.
   */
  int getSecurityValue();
  /**
   * <code>.com.wisekrakr.wisesecurecomm.communication.proto.MessageType.Security security = 4;</code>
   * @return The security.
   */
  com.wisekrakr.wisesecurecomm.communication.proto.MessageType.Security getSecurity();
}
