// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: MessageObject.proto

package com.wisekrakr.wisesecurecomm.communication.proto;

public interface MessageTypeOrBuilder extends
    // @@protoc_insertion_point(interface_extends:MessageType)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.MessageType.Message message = 1;</code>
   * @return The enum numeric value on the wire for message.
   */
  int getMessageValue();
  /**
   * <code>.MessageType.Message message = 1;</code>
   * @return The message.
   */
  MessageType.Message getMessage();

  /**
   * <code>.MessageType.Notifications notificiations = 2;</code>
   * @return The enum numeric value on the wire for notificiations.
   */
  int getNotificiationsValue();
  /**
   * <code>.MessageType.Notifications notificiations = 2;</code>
   * @return The notificiations.
   */
  MessageType.Notifications getNotificiations();

  /**
   * <code>.MessageType.Commands commands = 3;</code>
   * @return The enum numeric value on the wire for commands.
   */
  int getCommandsValue();
  /**
   * <code>.MessageType.Commands commands = 3;</code>
   * @return The commands.
   */
  MessageType.Commands getCommands();

  /**
   * <code>.MessageType.Security security = 4;</code>
   * @return The enum numeric value on the wire for security.
   */
  int getSecurityValue();
  /**
   * <code>.MessageType.Security security = 4;</code>
   * @return The security.
   */
  MessageType.Security getSecurity();
}
