// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: MessageObject.proto

package com.wisekrakr.wisesecurecomm.communication.proto;

public interface MessageObjectOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.wisekrakr.wisesecurecomm.communication.proto.MessageObject)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 id = 1;</code>
   * @return The id.
   */
  long getId();

  /**
   * <code>.com.wisekrakr.wisesecurecomm.communication.proto.MessageObject.ObjectType object_type = 2;</code>
   * @return The enum numeric value on the wire for objectType.
   */
  int getObjectTypeValue();
  /**
   * <code>.com.wisekrakr.wisesecurecomm.communication.proto.MessageObject.ObjectType object_type = 2;</code>
   * @return The objectType.
   */
  com.wisekrakr.wisesecurecomm.communication.proto.MessageObject.ObjectType getObjectType();

  /**
   * <code>.com.wisekrakr.wisesecurecomm.communication.proto.MessageType message_type = 3;</code>
   * @return Whether the messageType field is set.
   */
  boolean hasMessageType();
  /**
   * <code>.com.wisekrakr.wisesecurecomm.communication.proto.MessageType message_type = 3;</code>
   * @return The messageType.
   */
  com.wisekrakr.wisesecurecomm.communication.proto.MessageType getMessageType();
  /**
   * <code>.com.wisekrakr.wisesecurecomm.communication.proto.MessageType message_type = 3;</code>
   */
  com.wisekrakr.wisesecurecomm.communication.proto.MessageTypeOrBuilder getMessageTypeOrBuilder();

  /**
   * <code>string text_message = 4;</code>
   * @return The textMessage.
   */
  java.lang.String getTextMessage();
  /**
   * <code>string text_message = 4;</code>
   * @return The bytes for textMessage.
   */
  com.google.protobuf.ByteString
      getTextMessageBytes();

  /**
   * <code>bytes voice_message = 5;</code>
   * @return The voiceMessage.
   */
  com.google.protobuf.ByteString getVoiceMessage();

  /**
   * <code>.com.wisekrakr.wisesecurecomm.communication.proto.FileInfo file_info = 6;</code>
   * @return Whether the fileInfo field is set.
   */
  boolean hasFileInfo();
  /**
   * <code>.com.wisekrakr.wisesecurecomm.communication.proto.FileInfo file_info = 6;</code>
   * @return The fileInfo.
   */
  com.wisekrakr.wisesecurecomm.communication.proto.FileInfo getFileInfo();
  /**
   * <code>.com.wisekrakr.wisesecurecomm.communication.proto.FileInfo file_info = 6;</code>
   */
  com.wisekrakr.wisesecurecomm.communication.proto.FileInfoOrBuilder getFileInfoOrBuilder();

  /**
   * <code>int64 owner_id = 7;</code>
   * @return The ownerId.
   */
  long getOwnerId();

  /**
   * <code>repeated int64 recipients_ids = 8;</code>
   * @return A list containing the recipientsIds.
   */
  java.util.List<java.lang.Long> getRecipientsIdsList();
  /**
   * <code>repeated int64 recipients_ids = 8;</code>
   * @return The count of recipientsIds.
   */
  int getRecipientsIdsCount();
  /**
   * <code>repeated int64 recipients_ids = 8;</code>
   * @param index The index of the element to return.
   * @return The recipientsIds at the given index.
   */
  long getRecipientsIds(int index);
}
